name: Parsers test for PRs

on:
    workflow_dispatch:
    pull_request:
        paths:
            - 'src/main/kotlin/org/koitharu/kotatsu/parsers/**'

permissions:
    contents: read

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.2

            -   name: Set up Java environment
                uses: actions/setup-java@fe779bf55ef683c9413269276a7588bb9cedf07a # v5.2.0
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Set up Android SDK
                uses: android-actions/setup-android@v3

            -   name: Install Android SDK packages
                shell: bash
                run: |
                    set +o pipefail
                    yes 2> /dev/null | sdkmanager --licenses > /dev/null
                    set -o pipefail
                    sdkmanager "platforms;android-35" "build-tools;35.0.0"

            -   name: Set up Gradle environment
                uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

            -   name: Compile the Android build
                run: ./gradlew :app:assembleDebug
